apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ch6nrt0sx-go 
  janus-idp.io/tekton: ch6nrt0sx-go
  backstage.io/kubernetes-id: ch6nrt0sx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ch6nrt0sx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  