apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ch6nrt0sx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ch6nrt0sx-go 
  name: ch6nrt0sx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ch6nrt0sx-go 
